config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # Static pages
  root 'static_pages#index'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'

  # Collection (content of author's repositories) pages
  get 'collections/:author_username/:owner/:name/pages/index', to: 'collections#index'
  get 'collections/:author_username/:owner/:name/pages/*path', to: 'collections#show'

  # Account creation and sessions
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :administrators, only: %i[new create]
  namespace :sessions do
    resource :administrator, only: %i[new create destroy]
    resource :author, only: [:destroy]
  end

  namespace :webauthn do
    resources :credentials, only: %i[index create destroy] do
      post :options, on: :collection, as: 'options_for'
    end
    resource :authentication, controller: 'authentication', only: %i[new create] do
      post :options, on: :collection, as: 'options_for'
    end
  end
  get 'github/callback', to: 'auth/github#create'

  # User and Author settings
  namespace :settings do
    resource :account, only: [:show]
    resource :enable_author, controller: :enable_author, only: [:show]
    resource :author, only: %i[edit update]
    scope module: 'authors', path: 'author', as: 'author' do
      resources :repositories, except: [:show] do
        get :available, on: :collection
        resources :builds, only: [:index], controller: 'repositories/builds'
      end
    end

    root to: 'accounts#show'
  end

  # Answers and likes on collections pages
  scope '/questions/:question_id' do
    resources :answers, only: %i[index new create destroy]
  end
  resources :likes, only: %i[create destroy]

  # Administrator dashboard
  namespace :dashboard do
    resources :administrators, only: [:index]
    resources :authors, only: %i[index edit update]
    resources :autodesk_files, only: [:index, :show]
    resources :builds, only: %i[index show]
    resources :github_installations, only: [:index]
    resources :questions, only: [:index, :show]
    resources :repositories, only: [:index]
    resources :users, only: [:index]
    root to: 'authors#index'
  end

  resources :repositories, only: [:update] do
    patch :toggle_banned_status, on: :member
  end

  constraints(Constraints::AdministratorRouteConstraint.new) do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Webhooks
  post '/webhooks/github', to: 'webhooks/github#create'

  # Proxy
  get '/autodesk/viewer-proxy/derivativeservice/v2/:request_type/*path', to: 'proxy/autodesk#show'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  has_many :likes, dependent: :destroy

  validates :body, presence: true
  validates :user_id, uniqueness: { scope: :question_id, message: 'can only have one answer per question' }

  def liked_by_user(user)
    likes.find { |like| like.user == user }
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question, :authenticate_user!

  # GET /questions/:question_id/answers
  def index
    @answers = @question.answers.order(created_at: :desc)
  end

  # GET /questions/:question_id/answers/new
  def new
    @answer = @question.answers.build
  end

  # POST /questions/:question_id/answers
  def create
    @answer = @question.answers.build(answer_params)
    @answer.user = current_user
    if @answer.save
      respond_to do |format|
        format.html { redirect_to answers_path(@question.id) }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE /questions/:question_id/answers/:id
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_path(@question.id) }
      format.turbo_stream
    end
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/dashboard/answers_controller.rb
module Dashboard
  class AnswersController < Dashboard::ApplicationController
    def default_sorting_attribute
      :id
    end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/views/answers/_answer.html.erb
<%= turbo_frame_tag nested_dom_id(question, answer) do %>
  <div class="answer">
    <div class="answer__body"
         data-controller="read-more"
         data-read-more-truncate-class="line-clamp"
         data-action="resize@window->read-more#render">
      <p data-read-more-target="content"><%= answer.body %></p>

      <button class="link hide"
              data-read-more-target="moreButton"
              data-action="read-more#showMore">
        Show more
      </button>
      
      <button class="link hide"
        data-read-more-target="lessButton"
        data-action="read-more#showLess">
        Show less
      </button>
    </div>

    <div class="answer__footer">
      <p class="answer__footer__time"><%= time_ago_in_words(answer.created_at) %> ago</p>

      <div class="answer__footer__buttons">
        <%= render 'likes/like', answer: %>

        <% if answer.user == current_user %>
          <%= button_to answer_path(question.id, answer.id),
                        class: 'answer__footer__buttons--delete',
                        method: :delete,
                        form: { data: { turbo_confirm: 'Are you sure?' } } do %>
            <i class="fa-regular fa-trash-can fa-lg" aria-hidden="true" title="Delete answer"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/answers/create.turbo_stream.erb
<%= turbo_stream.update nested_dom_id(@question, Answer.new), "" %>

<%= turbo_stream.remove 'empty-state-answers' %>

<%= turbo_stream.prepend nested_dom_id(@question, 'answers') do %>
    <%= render @answer, question: @question %>
  <% end %>

app/views/answers/destroy.turbo_stream.erb
<%= turbo_stream.remove nested_dom_id(@question, @answer) %>

<% if @question.answers.none? %>
  <%= turbo_stream.prepend nested_dom_id(@question, 'answers') do %>
    <p id="empty-state-answers">No answers yet!</p>
  <% end %>
<% end %>

app/views/answers/index.html.erb
<% content_for(:html_title) { 'Answers' } %>

<h2>Question</h2>

<%= simple_format(@question.body) %>

<h2>Answers</h2>

<%= turbo_frame_tag nested_dom_id(@question, 'answers') do %>
  <% if @answers.empty? %>
    <p id="empty-state-answers">No answers yet!</p>
  <% else %>
    <div><%= render @answers, question: @question %></div>
  <% end %>

  <%= link_to 'Close', :back, class: 'button' %>
<% end %>

<br>
<%= link_to 'Add answer', new_answer_path(@question.id) %>

app/views/answers/new.html.erb
<% content_for(:html_title) { 'New answer' } %>

<h2>New answer</h2>

<%= turbo_frame_tag nested_dom_id(@question, 'new_answer') do %>
  <div class="form-block">
    <%= form_with model: @answer, url: answers_path  do |f| %>
      <%= render 'shared/form_errors', resource: @answer if @answer.errors.any? %>

      <div class="form-field">
        <%= f.text_area :body, required: true %>
        <%= f.label :body, 'Your answer...' %>
      </div>

      <%= f.submit %>
      <%= link_to 'Cancel', :back, class: 'button button-tertiary' %>
    <% end %>
  </div>
<% end %>