config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # Static pages
  root 'static_pages#index'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'

  # Collection (content of author's repositories) pages
  get 'collections/:author_username/:owner/:name/pages/index', to: 'collections#index'
  get 'collections/:author_username/:owner/:name/pages/*path', to: 'collections#show'

  # Account creation and sessions
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :administrators, only: %i[new create]
  namespace :sessions do
    resource :administrator, only: %i[new create destroy]
    resource :author, only: [:destroy]
  end

  namespace :webauthn do
    resources :credentials, only: %i[index create destroy] do
      post :options, on: :collection, as: 'options_for'
    end
    resource :authentication, controller: 'authentication', only: %i[new create] do
      post :options, on: :collection, as: 'options_for'
    end
  end
  get 'github/callback', to: 'auth/github#create'

  # User and Author settings
  namespace :settings do
    resource :account, only: [:show]
    resource :enable_author, controller: :enable_author, only: [:show]
    resource :author, only: %i[edit update]
    scope module: 'authors', path: 'author', as: 'author' do
      resources :repositories, except: [:show] do
        get :available, on: :collection
        resources :builds, only: [:index], controller: 'repositories/builds'
      end
    end

    root to: 'accounts#show'
  end

  # Answers and likes on collections pages
  scope '/questions/:question_id' do
    resources :answers, only: %i[index new create destroy]
  end
  resources :likes, only: %i[create destroy]

  # Administrator dashboard
  namespace :dashboard do
    resources :administrators, only: [:index]
    resources :authors, only: %i[index edit update]
    resources :autodesk_files, only: [:index, :show]
    resources :builds, only: %i[index show]
    resources :github_installations, only: [:index]
    resources :questions, only: [:index, :show]
    resources :repositories, only: [:index]
    resources :users, only: [:index]
    root to: 'authors#index'
  end

  resources :repositories, only: [:update] do
    patch :toggle_banned_status, on: :member
  end

  constraints(Constraints::AdministratorRouteConstraint.new) do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Webhooks
  post '/webhooks/github', to: 'webhooks/github#create'

  # Proxy
  get '/autodesk/viewer-proxy/derivativeservice/v2/:request_type/*path', to: 'proxy/autodesk#show'
end

app/controllers/author_admin/repositories_controller.rb
module AuthorAdmin
  class RepositoriesController < AuthorAdmin::ApplicationController
    # Override `create` action to add association to `current_author`
    # and to call background jobs
    def create
      params[:repository][:author_id] = current_author.id
      resource = new_resource(resource_params)
      authorize_resource(resource)

      if resource.save
        CreateGithubWebhookJob.perform_async(
          resource.uuid,
          resource.name,
          resource.author.github_username,
          resource.token
        )
        CloneGithubRepoJob.perform_async(resource.id)
        redirect_to(
          after_resource_created_path(resource),
          notice: translate_with_resource('create.success')
        )
      else
        render :new, locals: {
          page: Administrate::Page::Form.new(dashboard, resource)
        }, status: :unprocessable_entity
      end
    end

    # Override `update` action to call background jobs
    def update
      former_name = requested_resource.name
      former_branch = requested_resource.branch

      if requested_resource.update(resource_params)
        if former_name != requested_resource.name || former_branch != requested_resource.branch
          old_directory = Rails.root.join('repos', requested_resource.author.github_username, former_name)
          FileUtils.remove_dir(old_directory) if Dir.exist?(old_directory)
          CloneGithubRepoJob.perform_async(requested_resource.id)
        else
          PullGithubRepoJob.perform_async(requested_resource.id)
        end
        redirect_to(
          after_resource_updated_path(requested_resource),
          notice: translate_with_resource('update.success')
        )
      else
        render :edit, locals: {
          page: Administrate::Page::Form.new(dashboard, requested_resource)
        }, status: :unprocessable_entity
      end
    end

    # For `index` action, only show repositories belonging to the author currently authentified
    def scoped_resource
      @repositories = current_author.repositories if current_author
    end

    # Override `resource_params` to add `author_id` as an allowed field
    def resource_params
      params.require(resource_class.model_name.param_key)
            .permit(dashboard.permitted_attributes(action_name) << :author_id)
            .transform_values { |v| read_param_value(v) }
    end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/author_dashboard/repositories_controller.rb
module AuthorDashboard
  class RepositoriesController < AuthorDashboard::ApplicationController
    # Override `create` action to add association to `current_author`
    # and to call background jobs
    def create
      params[:repository][:author_id] = current_author.id
      resource = new_resource(resource_params)
      authorize_resource(resource)

      if resource.save
        CreateGithubWebhookJob.perform_async(
          resource.uuid,
          resource.name,
          resource.author.github_username,
          resource.token
        )
        CloneGithubRepoJob.perform_async(resource.id)
        redirect_to(
          after_resource_created_path(resource),
          notice: translate_with_resource('create.success')
        )
      else
        render :new, locals: {
          page: Administrate::Page::Form.new(dashboard, resource)
        }, status: :unprocessable_entity
      end
    end

    # Override `update` action to call background jobs
    def update
      former_name = requested_resource.name
      former_branch = requested_resource.branch

      if requested_resource.update(resource_params)
        if former_name != requested_resource.name || former_branch != requested_resource.branch
          old_directory = Rails.root.join('repos', requested_resource.author.github_username, former_name)
          FileUtils.remove_dir(old_directory) if Dir.exist?(old_directory)
          CloneGithubRepoJob.perform_async(requested_resource.id)
        else
          PullGithubRepoJob.perform_async(requested_resource.id)
        end
        redirect_to(
          after_resource_updated_path(requested_resource),
          notice: translate_with_resource('update.success')
        )
      else
        render :edit, locals: {
          page: Administrate::Page::Form.new(dashboard, requested_resource)
        }, status: :unprocessable_entity
      end
    end

    # For `index` action, only show repositories belonging to the author currently authentified
    def scoped_resource
      @repositories = current_author.repositories if current_author
    end

    # Override `resource_params` to add `author_id` as an allowed field
    def resource_params
      params.require(resource_class.model_name.param_key)
            .permit(dashboard.permitted_attributes(action_name) << :author_id)
            .transform_values { |v| read_param_value(v) }
    end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/dashboard/authors_controller.rb
module Dashboard
  class AuthorsController < Dashboard::ApplicationController
    def after_resource_updated_path(_requested_resource)
      dashboard_authors_path
    end

    def default_sorting_attribute
      :id
    end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/dashboard/repositories_controller.rb
module Dashboard
  class RepositoriesController < Dashboard::ApplicationController
    def default_sorting_attribute
      :id
    end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :require_author_or_admin_authentication, only: [:update]
  before_action :require_administrator_authentication, only: [:toggle_banned_status]
  before_action :set_repository

  # PATCH /repositories/:id
  def update
    build = Build.create(repository: @repository, status: 'In progress', action: 'rebuild')
    build.rebuild_repo
    notice_msg = 'Repository rebuild process was initiated. Check Builds for progress and details.'
    if current_administrator
      redirect_to dashboard_repositories_path, notice: notice_msg
    elsif current_author
      redirect_to settings_author_repositories_path, notice: notice_msg
    end
  end

  # PATCH /repositories/:id/toggle_banned_status
  def toggle_banned_status
    @repository.toggle!(:banned)
    redirect_to dashboard_repositories_path
  end

  private

  def set_repository
    @repository = Repository.find_by(id: params[:id])
  end

  def require_author_or_admin_authentication
    repository = Repository.find(params[:id])
    return if administrator_signed_in? || current_author.id == repository.author.id

    redirect_to root_path, alert: 'Please log in as an author or administrator.'
  end
end

app/controllers/settings/authors/repositories/builds_controller.rb
module Settings
  module Authors
    module Repositories
      class BuildsController < ApplicationController
        before_action :require_author_authentication, :set_repository

        # GET /settings/author/repositories/:repository_id/builds
        def index
          @builds = @repository.builds.order(created_at: :desc)
        end

        private

        def set_repository
          @repository = Repository.includes(:github_installation)
                                  .find_by(id: params[:repository_id],
                                           github_installation: { author_id: current_author.id })
        end
      end
    end
  end
end

app/controllers/settings/authors/repositories_controller.rb
module Settings
  module Authors
    class RepositoriesController < ApplicationController
      layout 'settings'

      before_action :require_author_authentication
      before_action :set_repository, only: %i[edit update destroy]
      before_action :set_available_repositories, only: %i[available new]
      before_action :verify_if_available_repository, only: [:new]

      # GET /settings/author/repositories
      def index
        @repositories = current_author.repositories.order('id ASC')
      end

      # GET /settings/author/repositories/available
      def available; end

      # GET /settings/author/repositories/new
      def new
        full_name = params[:full_name]
        owner, name = full_name.split('/')
        @repository = github_installation(owner).repositories.build(name:, uid: params[:uid].to_i)
      end

      # GET /settings/author/repositories/:id/edit
      def edit; end

      # POST /settings/author/repositories
      def create
        @repository = github_installation(repository_params[:owner]).repositories
                                                                    .build(repository_params.except(:owner))
        if @repository.save
          build = Build.create(repository: @repository, status: 'In progress', action: 'create')
          build.create_repo
          redirect_to settings_author_repositories_path,
                      notice: 'Repository creation process was initiated. Check Builds for progress and details.'
        else
          render :new, status: :unprocessable_entity
        end
      end

      # PATCH /settings/author/repositories/:id
      def update
        former_branch = @repository.branch

        if @repository.update(repository_params.except(:owner))
          build = Build.create(repository: @repository, status: 'In progress', action: 'update')
          directory = @repository.storage_path
          update_actions(build, directory, former_branch)
          redirect_to settings_author_repositories_path,
                      notice: 'Repository update process was initiated. Check Builds for progress and details.'
        else
          render :edit, status: :unprocessable_entity
        end
      end

      # DELETE /settings/author/repositories/:id
      def destroy
        RemoveDirectoryJob.perform_async(@repository.storage_path.to_s)
        @repository.destroy
        redirect_to settings_author_repositories_path, notice: 'Repository was successfully deleted.'
      end

      private

      def set_repository
        @repository = Repository.includes(:github_installation)
                                .find_by(id: params[:id], github_installation: { author_id: current_author.id })
      end

      def repository_params
        params.require(:repository).permit(:uid, :name, :owner, :branch, :title)
      end

      def github_installation(username)
        GithubInstallation.find_by(author_id: current_author.id, username:)
      end

      def update_actions(build, directory, former_branch)
        if former_branch == @repository.branch
          build.update_repo('pull')
        else
          FileUtils.rm_r(directory) if Dir.exist?(directory)
          build.update_repo('clone')
        end
      end

      def set_available_repositories
        @available_repositories = current_author.repositories_available_for_addition
      rescue Octokit::NotFound
        github_app_name = ENV.fetch('GITHUB_APP_NAME', Rails.application.credentials.dig(:github, :app_name))
        alert = <<-MSG
        It looks like we don't have access to your GitHub account anymore.
        Visit #{view_context.link_to 'this page', "https://github.com/apps/#{github_app_name}/installations/new"}
        to link your account.
        MSG
        redirect_to settings_root_path, alert:
      end

      def verify_if_available_repository
        return if @available_repositories.include?({ full_name: params[:full_name], uid: params[:uid].to_i })

        redirect_to root_path, alert: 'You are not have permission to add this repository.'
      end
    end
  end
end

app/controllers/settings/authors_controller.rb
module Settings
  class AuthorsController < ApplicationController
    layout 'settings'

    before_action :require_author_authentication, :set_author

    # GET /settings/author/edit
    def edit; end

    # PATCH /settings/author
    def update
      if @author.update(author_params)
        redirect_to edit_settings_author_path, notice: 'Author was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def set_author
      @author = Author.find(current_author.id)
    end

    def author_params
      params.require(:author).permit(:name)
    end
  end
end

app/controllers/system_admin/authors_controller.rb
module SystemAdmin
  class AuthorsController < SystemAdmin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/system_dashboards/authors_controller.rb
module SystemDashboards
  class AuthorsController < SystemDashboards::ApplicationController
    def after_resource_updated_path(_requested_resource)
      system_dashboards_authors_path
    end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/views/settings/authors/repositories/_form.html.erb
<%= form_with(model: [:settings, :author, repository]) do |form| %>
  <%= render 'shared/form_errors', resource: repository if repository.errors.any? %>

  <p><%= "Name: #{repository.name}" %></p>
  <%= form.hidden_field :name, value: repository.name %>

  <p><%= "Owner: #{repository.owner}" %></p>
  <%= form.hidden_field :owner, value: repository.owner %>

  <%= form.hidden_field :uid, value: repository.uid %>

  <div class="form-field">
    <%= form.text_field :branch %>
    <%= form.label :branch, 'Branch (if other than main)' %>
  </div>

  <div class="form-field">
    <%= form.text_field :title, required: true %>
    <%= form.label :title, 'Title' %>
  </div>

  <%= form.submit %>
<% end %>

app/views/settings/authors/repositories/available.html.erb
<% content_for(:html_title) { 'Available Repositories - Settings' } %>

<div class="form-block">
  <h2>Available Repositories</h2>

  <h5>
    <% github_app_name = ENV.fetch('GITHUB_APP_NAME', Rails.application.credentials.dig(:github, :app_name))%> 
    Choose from one of the repositories below. If the repository you want is not listed, check your
    <%= link_to 'GitHub settings', "https://github.com/apps/#{github_app_name}/installations/new", target: :_blank %>
    to verify that is can be accessed by KnewHub.
  </h5>

  <ul>
    <% if @available_repositories %>
      <% @available_repositories.each do |repository| %>
        <li>
            <%= repository[:full_name] %>
            <%= link_to 'Add repository',
                          new_settings_author_repository_path(full_name: repository[:full_name], uid: repository[:uid]),
                          class: 'button' %>
          </li>
      <% end %>
    <% else %>
      <p>No available repositories</p>
    <% end %>
  </ul>
</div>

app/views/settings/authors/repositories/edit.html.erb
<% content_for(:html_title) { "Edit Repository - Settings" } %>

<div class="edit-repository form-block">
  <div class="edit-repository__header">
    <h1><%= "Edit Repository" %></h1>

    <%= button_to 'Delete Repository',
                    settings_author_repository_path(@repository),
                    method: :delete,
                    form: { data: { turbo_confirm: 'Are you sure?' } },
                    class: 'edit-author-repository__button' %>
  </div>
  
  <%= render 'form', repository: @repository %>
  
  <br />
  <%= button_to 'Rebuild repository (pull from GitHub)', repository_path(@repository), method: :patch, class: 'link' %>
  <%= link_to 'Back to repositories', settings_author_repositories_path %>
</div>

app/views/settings/authors/repositories/index.html.erb
<% content_for(:html_title) { 'Repositories - Settings' } %>

<div class="index-repositories form-block">
  <h2><%= "#{current_author.name}'s Repositories" %></h2>

  <div class="index-repositories__grid">
    <% @repositories.each do |repository| %>
      <div class="index-repositories__card">
        <div class="index-repositories__card__text">
          <div class="index-repositories__card__line">
            Name: <%= repository.name %>
          </div>

          <div class="index-repositories__card__line">
            Title: <%= repository.title %>
          </div>

          <div class="index-repositories__card__line">
            Branch:
            <span class="index-repositories__card__branch"><%= repository.branch %></span>
          </div>
          
          <div class="index-repositories__card__line">
            Last build: 
            <%= build_status_icon(repository.builds.last) %>
            <span class="sr-only"><%= repository.builds.last&.status %></span>
            <%= build_information(repository.builds.last) %>
          </div>
        </div>
        
        <div class="index-repositories__card__actions">
          <%= link_to 'View book',
                      "/collections/#{repository.storage}/pages/index",
                      target: :_blank,
                      class: 'button button-small button-tertiary',
                      disabled: !repository.visible?,
                      title: "#{repository.visible? ? '' : 'This repository is disabled' }" %>
          <%= link_to 'Edit', edit_settings_author_repository_path(repository.id), class: 'button button-small' %>
          <%= link_to 'Show builds', settings_author_repository_builds_path(repository.id), class: 'button button-small' %>
        </div>
      </div>
    <% end %>     
  </div>

  <%= link_to 'New repository', available_settings_author_repositories_path, class: 'button' %>
</div>

app/views/settings/authors/repositories/new.html.erb
<% content_for(:html_title) { 'New repository - Settings' } %>

<div class="form-block">
  <h1>New repository</h1>

  <%= render 'form', repository: @repository %>
  
  <%= link_to 'Back to repositories', settings_author_repositories_path %>
</div>